runtime: python312
env: standard

instance_class: F2

entrypoint: gunicorn -b :$PORT --chdir server app:app --timeout 300 --workers 2

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.65

env_variables:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  GEMINI_API_KEY: "AIzaSyA6kq64Orix7QlkbapiF1ZcjrTypFFahJo"

handlers:
  # API routes
  - url: /api/.*
    script: auto

  # React static files
  - url: /static
    static_dir: client/build/static

  # Other assets
  - url: /(.*\.(json|ico|png|jpg|jpeg|svg|txt))
    static_files: client/build/\1
    upload: client/build/.*

  # ALL React routes (IMPORTANT)
  - url: /.*
    static_files: client/build/index.html
    upload: client/build/index.html





















# runtime: python312

# env: standard

# instance_class: F2

# entrypoint: gunicorn -b :$PORT --chdir server app:app --timeout 300 --workers 2

# automatic_scaling:
#   min_instances: 0
#   max_instances: 5
#   target_cpu_utilization: 0.65

# env_variables:
#   GEMINI_API_KEY: "AIzaSyA6kq64Orix7QlkbapiF1ZcjrTypFFahJo"
#   FLASK_ENV: "production"
#   PYTHONUNBUFFERED: "1"
